# Generated by Django 3.0.5 on 2020-04-29 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='submissionDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
