# Generated by Django 3.1.1 on 2020-10-14 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200429_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('code_src', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='submissionDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
