# Generated by Django 3.1.1 on 2020-10-15 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201014_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(max_length=30)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.language')),
            ],
        ),
        migrations.CreateModel(
            name='JobNoFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
                ('submissionDate', models.DateField(blank=True, default=datetime.date.today)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.language')),
            ],
        ),
        migrations.CreateModel(
            name='JobYesFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
                ('submissionDate', models.DateField(blank=True, default=datetime.date.today)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.framework')),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
