# Generated by Django 3.1.1 on 2020-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_framework_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnoframework',
            name='paste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobnoframework',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobyesframework',
            name='paste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobyesframework',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
