# Generated by Django 3.1.1 on 2020-10-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='name',
            field=models.CharField(default='Brenden Price', max_length=30),
        ),
    ]
